CREATE DATABASE PolPromad;

CREATE TABLE IF NOT EXISTS public.processos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_processo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT processos_pkey PRIMARY KEY (id),
    CONSTRAINT ukkrxbuvsmkvvvdrakc8w14jkip UNIQUE (numero_processo)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.processos
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.reus
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    processo_id bigint NOT NULL,
    CONSTRAINT reus_pkey PRIMARY KEY (id),
    CONSTRAINT fkt5upoxcm4hh9se386cy0ee1y4 FOREIGN KEY (processo_id)
        REFERENCES public.processos (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.reus
    OWNER to postgres;